### ISSUE TITLE
1.2.0 breaks builds because of wrong versionCode integer to string conversion

### ISSUE THREAD

**Issue by tlow92** [bitrise-steplib/steps-change-android-versioncode-and-versionname#16] opened 2019-11-08 16:34 UTC
1.2.0 breaks my builds because it encodes versionCode into unicode characters.

```
updating line (101):         versionCode 46 ->         versionCode 846
updating line (102):         versionName "2.5.4" ->         versionName "2.5.31"
```

turns into 
```
updating line (101):         versionCode 46 ->         versionCode ͍
updating line (102):         versionName "2.5.4" ->         versionName "2.5.31"
```

I guess the problem lies in just converting the int with string() in the following part:
https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/commit/638551a410bd4355239d3f669cad7c80a1ee29ca#diff-7ddfb3e035b42cd70649cc33393fe32cR105

**Comment by XinyueZ** [comment] 2019-11-08 21:59
<img width="831" alt="Screenshot 2019-11-08 at 21 39 09" src="https://user-images.githubusercontent.com/7869833/68513464-5fd13300-027b-11ea-9a06-56c6ac12c706.png">

**Comment by XinyueZ** [comment] 2019-11-08 21:59
+1

**Comment by eliserichards** [comment] 2019-11-09 01:44
Casting an int to a string (NewVersionCode) interprets the int as a rune. This results in the finalVersionCode string being the codepoint for the corresponding sum of version code and offset.

**Comment by odemolliens** [comment] 2019-11-10 09:20
+1

Here we get chinese character instead of the versionCode

```
+------------------------------------------------------------------------------+
| (1) Android - Set version code and name |
+------------------------------------------------------------------------------+
| id: change-android-versioncode-and-versionname |
| version: 1.2.0 |
| collection: https://github.com/bitrise-io/bitrise-steplib.git |
| toolkit: go |
| time: 2019-11-10T08:59:55Z |
+------------------------------------------------------------------------------+
| |
Config:
- BuildGradlePth: android/app/build.gradle
- NewVersionName: 5.0.0
- NewVersionCode: 26548
- VersionCodeOffset: 0


Updating versionName and versionCode in: android/app/build.gradle
updating line (60): versionCode 666 -> versionCode 枴
updating line (61): versionName "1.0.0" -> versionName "1.0.0"
updating line (228): versionCodes.get(abi) * 1048576 + defaultConfig.versionCode -> versionCode枴 * 1048576 + defaultConfig.versionCode

2 versionCode updated
1 versionName updated
| |
+---+---------------------------------------------------------------+----------+
| ✓ | Android - Set version code and name | 24.64 sec|
+---+---------------------------------------------------------------+----------+
```

```
* Where:
Build file '/Users/vagrant/git/android/app/build.gradle' line: 61

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property '枴' for DefaultConfig_Decorated
```

**Comment by trapacska** [comment] 2019-11-11 10:40
Going to be released within the next 30 minutes. Thanks!
https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.1

**Comment by trapacska** [comment] 2019-11-11 11:00
The release is now available in our StepLib. Please update to the latest 1.2.1 version. Closing the issue as it is fixed, feel free to re-open if the issue is still existing.

Thank you for reporting!
🚀

**Closed by trapacska** 2019-11-11 11:00 UTC

**Comment by YevheniyDovbnya** [comment] 2019-11-11 11:06
Thanks, when will it be accessible as Bitrise step?
